/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VerifyTokenResponse } from '../../models/verify-token-response';

export interface VerifyToken$Params {
  token: string;
}

export function verifyToken(http: HttpClient, rootUrl: string, params: VerifyToken$Params, context?: HttpContext): Observable<StrictHttpResponse<VerifyTokenResponse>> {
  const rb = new RequestBuilder(rootUrl, verifyToken.PATH, 'get');
  if (params) {
    rb.query('token', params.token, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VerifyTokenResponse>;
    })
  );
}

verifyToken.PATH = '/api/auth/verify';
