AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for the Etalente Frontend ECS Service

Parameters:
  ProjectName:
    Type: String
    Default: etalente
    Description: Name of the project
  FrontendImageUri:
    Type: String
    Description: ECR URI for the frontend Docker image

Resources:
  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-frontend-ecs-task-execution-role

  FrontendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${ProjectName}-frontend-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt EcsTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: !Sub ${ProjectName}-frontend-container
          Image: !Ref FrontendImageUri
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-frontend-task

  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${ProjectName}-frontend
      RetentionInDays: 30
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-frontend-log-group

  FrontendEcsService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !ImportValue
        Fn::Sub: '${ProjectName}-EcsClusterName'
      ServiceName: !Sub ${ProjectName}-frontend-service
      TaskDefinition: !Ref FrontendTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !ImportValue
              Fn::Sub: '${ProjectName}-PrivateSubnet1aId'
            - !ImportValue
              Fn::Sub: '${ProjectName}-PrivateSubnet1bId'
          SecurityGroups:
            - !ImportValue
              Fn::Sub: '${ProjectName}-EcsTasksSecurityGroupId'
      LoadBalancers:
        - ContainerName: !Sub ${ProjectName}-frontend-container
          ContainerPort: 80
          TargetGroupArn: !ImportValue
            Fn::Sub: '${ProjectName}-FrontendTargetGroupArn'
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-frontend-service

Outputs:
  FrontendTaskDefinitionArn:
    Description: The ARN of the Frontend Task Definition
    Value: !Ref FrontendTaskDefinition
    Export:
      Name: !Sub ${ProjectName}-FrontendTaskDefinitionArn
  FrontendEcsServiceArn:
    Description: The ARN of the Frontend ECS Service
    Value: !Ref FrontendEcsService
    Export:
      Name: !Sub ${ProjectName}-FrontendEcsServiceArn