/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationSummaryDto } from '../../models/application-summary-dto';

export interface ApplyForJob$Params {
  id: string;
}

export function applyForJob(http: HttpClient, rootUrl: string, params: ApplyForJob$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicationSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, applyForJob.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApplicationSummaryDto>;
    })
  );
}

applyForJob.PATH = '/api/job-posts/{id}/apply';
