/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageApplicationSummaryDto } from '../../models/page-application-summary-dto';

export interface GetMyApplications$Params {
  pageable: Pageable;
  search?: string;
  sort?: string;
}

export function getMyApplications(http: HttpClient, rootUrl: string, params: GetMyApplications$Params, context?: HttpContext): Observable<StrictHttpResponse<PageApplicationSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, getMyApplications.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
    rb.query('search', params.search, {});
    rb.query('sort', params.sort, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageApplicationSummaryDto>;
    })
  );
}

getMyApplications.PATH = '/api/applications/me';
