/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RecruiterInvitationDto } from '../../models/recruiter-invitation-dto';
import { RecruiterInvitationRequest } from '../../models/recruiter-invitation-request';

export interface InviteRecruiter$Params {
      body: RecruiterInvitationRequest
}

export function inviteRecruiter(http: HttpClient, rootUrl: string, params: InviteRecruiter$Params, context?: HttpContext): Observable<StrictHttpResponse<RecruiterInvitationDto>> {
  const rb = new RequestBuilder(rootUrl, inviteRecruiter.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RecruiterInvitationDto>;
    })
  );
}

inviteRecruiter.PATH = '/api/invitations/recruiter';
