/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowTriggerRequest } from '../../models/workflow-trigger-request';
import { WorkflowTriggerResponse } from '../../models/workflow-trigger-response';

export interface TriggerWorkflow$Params {
  workflowId: string;
      body: WorkflowTriggerRequest
}

export function triggerWorkflow(http: HttpClient, rootUrl: string, params: TriggerWorkflow$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowTriggerResponse>> {
  const rb = new RequestBuilder(rootUrl, triggerWorkflow.PATH, 'post');
  if (params) {
    rb.path('workflowId', params.workflowId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowTriggerResponse>;
    })
  );
}

triggerWorkflow.PATH = '/api/v1/workflows/{workflowId}/trigger';
