/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AcceptInvitationRequest {
  contactNumber: string;
  firstName: string;
  lastName: string;
  password?: string;
  username: string;
}
