/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JobSummaryDto } from '../models/job-summary-dto';
export interface ApplicationSummaryDto {
  applicationDate?: string;
  id?: string;
  job?: JobSummaryDto;
  status?: string;
}
