/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommunicationHistoryDto } from '../models/communication-history-dto';
import { JobPostDto } from '../models/job-post-dto';
export interface ApplicationDetailsDto {
  applicationDate?: string;
  communicationHistory?: Array<CommunicationHistoryDto>;
  id?: string;
  job?: JobPostDto;
  status?: string;
}
