/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HiringManagerRegistrationDto {
  companyName: string;
  contactNumber: string;
  contactPerson: string;
  industry: string;
  username: string;
}
