/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LocationDto {
  address?: string;
  city: string;
  countryCode: string;
  postalCode?: string;
  region?: string;
}
