/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationRequest {
  content: string;
  metadata?: {
[key: string]: any;
};
  recipientId: string;
  title: string;
  type: string;
}
