/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationResponse {
  content?: string;
  createdAt?: string;
  id?: number;
  metadata?: {
[key: string]: any;
};
  readAt?: string;
  recipientId?: string;
  status?: 'PENDING' | 'SENT' | 'DELIVERED' | 'READ' | 'FAILED';
  title?: string;
  type?: string;
}
