/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RecruiterInvitationDto {
  createdAt?: string;
  email?: string;
  expiresAt?: string;
  id?: string;
  status?: 'PENDING' | 'ACCEPTED' | 'EXPIRED' | 'REVOKED';
}
