/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SessionResponse {
  authenticated?: boolean;
  email?: string;
  expiresIn?: number;
  isNewUser?: boolean;
  role?: string;
  userId?: string;
}
