/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowTriggerRequest {
  email?: string;
  firstName?: string;
  lastName?: string;
  payload: {
[key: string]: any;
};
  subscriberId: string;
}
