/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompleteProfileRequest } from '../../models/complete-profile-request';
import { VerifyTokenResponse } from '../../models/verify-token-response';

export interface CompleteProfile$Params {
      body: CompleteProfileRequest
}

export function completeProfile(http: HttpClient, rootUrl: string, params: CompleteProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<VerifyTokenResponse>> {
  const rb = new RequestBuilder(rootUrl, completeProfile.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VerifyTokenResponse>;
    })
  );
}

completeProfile.PATH = '/api/profile/complete';
