/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StateAuditResponse } from '../../models/state-audit-response';

export interface GetStateHistory$Params {
  id: string;
}

export function getStateHistory(http: HttpClient, rootUrl: string, params: GetStateHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StateAuditResponse>>> {
  const rb = new RequestBuilder(rootUrl, getStateHistory.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StateAuditResponse>>;
    })
  );
}

getStateHistory.PATH = '/api/job-posts/{id}/history';
