/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageJobPostResponse } from '../../models/page-job-post-response';

export interface ListJobPosts$Params {
  pageable: Pageable;
  search?: string;
  skillSearch?: string;
  experienceLevels?: Array<string>;
  jobTypes?: Array<string>;
  workTypes?: Array<string>;
}

export function listJobPosts(http: HttpClient, rootUrl: string, params: ListJobPosts$Params, context?: HttpContext): Observable<StrictHttpResponse<PageJobPostResponse>> {
  const rb = new RequestBuilder(rootUrl, listJobPosts.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
    rb.query('search', params.search, {});
    rb.query('skillSearch', params.skillSearch, {});
    rb.query('experienceLevels', params.experienceLevels, {});
    rb.query('jobTypes', params.jobTypes, {});
    rb.query('workTypes', params.workTypes, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageJobPostResponse>;
    })
  );
}

listJobPosts.PATH = '/api/job-posts';
