/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JobPostRequest } from '../../models/job-post-request';
import { JobPostResponse } from '../../models/job-post-response';

export interface UpdateJobPost$Params {
  id: string;
      body: JobPostRequest
}

export function updateJobPost(http: HttpClient, rootUrl: string, params: UpdateJobPost$Params, context?: HttpContext): Observable<StrictHttpResponse<JobPostResponse>> {
  const rb = new RequestBuilder(rootUrl, updateJobPost.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JobPostResponse>;
    })
  );
}

updateJobPost.PATH = '/api/job-posts/{id}';
