#!/bin/bash

# Define paths
API_DIR="src/app/api"
BASE_SERVICE_PATH="$API_DIR/base-service.ts"

# 1. Run ng-openapi-gen
echo "Running ng-openapi-gen..."
npx ng-openapi-gen --input http://localhost:8080/v3/api-docs --output $API_DIR --services true --promises false

# 2. Restore base-service.ts
echo "Restoring base-service.ts..."
cat << 'EOF' > $BASE_SERVICE_PATH
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration } from './api-configuration';

/**
 * Base class for services
 */
@Injectable()
export class BaseService {
  constructor(
    protected config: ApiConfiguration,
    protected http: HttpClient
  ) {
  }

  private _rootUrl?: string;

  /**
   * Returns the root url for all operations in this service. If not set directly in this
   * service, will fallback to `ApiConfiguration.rootUrl`.
   */
  get rootUrl(): string {
    return this._rootUrl || this.config.rootUrl;
  }

  /**
   * Sets the root URL for API operations in this service.
   */
  set rootUrl(rootUrl: string) {
    this._rootUrl = rootUrl;
  }
}
EOF

echo "API client generation and restoration complete."
